export const GET_CALENDAR_ENTRIES = "@Calendar/GET_CALENDAR_ENTRIES";
export const ADD_OR_UPDATE_CALENDAR_ENTRY = "@Calendar/ADD_OR_UPDATE_CALENDAR_ENTRY";
export const SET_SELECTED_CALENDAR_MONTH = "@Calendar/SET_SELECTED_CALENDAR_MONTH";
export const DELETE_CALENDAR_ENTRY = "@Calendar/DELETE_CALENDAR_ENTRY";
