export const GET_LOGGED_USER_INFO = '@Employee/GET_LOGGED_USER_INFO';
export const ADD_OR_UPDATE_EMPLOYEE_INFO = '@Employee/ADD_OR_UPDATE_EMPLOYEE_INFO';
export const GET_ALL_EMPLOYEES = '@Employee/GET_ALL_EMPLOYEES';
export const DELETE_EMPLOYEE = '@Employee/DELETE_EMPLOYEE';
